"""Constants for Date Countdown integration."""

import logging

_LOGGER = logging.getLogger(__name__)

DOMAIN = "date_countdown"
PLATFORMS = ["sensor", "calendar"]
DATE_FORMAT = "DD/MM/YYYY"
EVENT_TYPES = ["birthday", "anniversary", "memorial", "promotion", "special_event", "retirement"]

# Catégories d'âge pour les anniversaires, une pour chaque âge de 0 à 120 ans
AGE_CATEGORIES = {
    (0, 0): "Mini Big Bang",
    (1, 1): "Bébé Fusée",
    (2, 2): "Tornade de Gribouilles",
    (3, 3): "Pirate des Bacs à Sable",
    (4, 4): "Ninja des Gâteaux",
    (5, 5): "Roi des Toboggans",
    (6, 6): "Artiste des Stickers",
    (7, 7): "Champion des Roulettes",
    (8, 8): "Maître des Legos",
    (9, 9): "Empereur des Cabanes",
    (10, 10): "As des Cartes Pokémon",
    (11, 11): "Pré-Ado TikTokeur",
    (12, 12): "Rebelle des Émojis",
    (13, 13): "Guru des Memes",
    (14, 14): "Ninja des Selfies",
    (15, 15): "Philosophe des Hashtags",
    (16, 16): "Roi des Stories Snapchat",
    (17, 17): "Visionnaire des Reels",
    (18, 18): "Majeur",
    (19, 19): "Sorcier des Festivals",
    (20, 20): "Ninja des Apéros",
    (21, 21): "Maître des Soirées Impro",
    (22, 22): "Jedi des Group Chats",
    (23, 23): "Guru des Playlists Spotify",
    (24, 24): "As des Brunchs",
    (25, 25): "Super-Héros des To-Do Lists",
    (26, 26): "Rockstar des Dimanches Netflix",
    (27, 27): "Sorcier des Excuses Créatives",
    (28, 28): "Empereur des Karaokés",
    (29, 29): "Maître des Challenges TikTok",
    (30, 30): "Guru des Brunchs",
    (31, 31): "Ninja des Réunions Zoom",
    (32, 32): "Jedi des Spreadsheets",
    (33, 33): "As des Apéros Vins",
    (34, 34): "Super-Héros du Multitasking",
    (35, 35): "Rockstar des Anniversaires",
    (36, 36): "Sorcier des BBQ",
    (37, 37): "Maître des Blagues Carambar",
    (38, 38): "Empereur des Soirées Quiz",
    (39, 39): "Guru des Astuces Cuisine",
    (40, 40): "Ninja des Parents Débordés",
    (41, 41): "Jedi des Vacances Planifiées",
    (42, 42): "As des Jeux de Société",
    (43, 43): "Super-Héros des Excuses Épiques",
    (44, 44): "Rockstar des Réunions Parents-Profs",
    (45, 45): "Sorcier des Budgets Serrés",
    (46, 46): "Maître des Anecdotes Drôles",
    (47, 47): "Empereur des Barbecues",
    (48, 48): "Guru des Soirées Nostalgie",
    (49, 49): "Ninja des Projets DIY",
    (50, 50): "Rockstar des Blagues de Papa",
    (51, 51): "Jedi des Siestes Impromptues",
    (52, 52): "As des Histoires de Jeunesse",
    (53, 53): "Super-Héros des Années 80",
    (54, 54): "Sorcier des Recettes de Grand-Mère",
    (55, 55): "Maître des Jeux de Cartes",
    (56, 56): "Empereur des Randonnées",
    (57, 57): "Guru des Conseils Sages",
    (58, 58): "Ninja des Soirées Tricot",
    (59, 59): "Jedi des Documentaires",
    (60, 60): "Rockstar des Siestes Épiques",
    (61, 61): "As des Mots Fléchés",
    (62, 62): "Super-Héros des Jardins",
    (63, 63): "Sorcier des Histoires Épiques",
    (64, 64): "Maître des Soirées Scrabble",
    (65, 65): "Empereur des Balades",
    (66, 66): "Guru des Souvenirs",
    (67, 67): "Ninja des Petits-Enfants",
    (68, 68): "Jedi des Anecdotes",
    (69, 69): "As des Soirées Bingo",
    (70, 70): "Rockstar des Récits d’Antan",
    (71, 71): "Super-Héros des Potagers",
    (72, 72): "Sorcier des Contes",
    (73, 73): "Maître des Puzzles",
    (74, 74): "Empereur des Souvenirs",
    (75, 75): "Guru des Balancelles",
    (76, 76): "Ninja des Histoires",
    (77, 77): "Jedi des Siestes",
    (78, 78): "As des Récits Légendaires",
    (79, 79): "Rockstar des Souvenirs",
    (80, 80): "Sage des Anecdotes Épiques",
    (81, 81): "Super-Héros des Récits",
    (82, 82): "Sorcier des Mémoires",
    (83, 83): "Maître des Histoires",
    (84, 84): "Empereur des Légendes",
    (85, 85): "Guru des Contes Épiques",
    (86, 86): "Ninja des Souvenirs",
    (87, 87): "Jedi des Récits",
    (88, 88): "As des Anecdotes",
    (89, 89): "Rockstar des Mémoires",
    (90, 90): "Sage des Légendes",
    (91, 91): "Super-Héros des Contes",
    (92, 92): "Sorcier des Souvenirs",
    (93, 93): "Maître des Récits Épiques",
    (94, 94): "Empereur des Mémoires",
    (95, 95): "Guru des Histoires",
    (96, 96): "Ninja des Légendes",
    (97, 97): "Jedi des Anecdotes",
    (98, 98): "As des Contes",
    (99, 99): "Rockstar des Souvenirs",
    (100, 100): "Légende Cosmique",
    (101, 101): "Super-Héros Intergalactique",
    (102, 102): "Sorcier des Étoiles",
    (103, 103): "Maître des Constellations",
    (104, 104): "Empereur des Galaxies",
    (105, 105): "Guru des Univers",
    (106, 106): "Ninja des Comètes",
    (107, 107): "Jedi des Astres",
    (108, 108): "As des Nébuleuses",
    (109, 109): "Rockstar des Étoiles",
    (110, 110): "Sage des Voies Lactées",
    (111, 111): "Super-Héros des Supernovas",
    (112, 112): "Sorcier des Pulsars",
    (113, 113): "Maître des Quasars",
    (114, 114): "Empereur des Trou Noirs",
    (115, 115): "Guru des Météores",
    (116, 116): "Ninja des Aurores",
    (117, 117): "Jedi des Éclipses",
    (118, 118): "As des Novas",
    (119, 119): "Rockstar des Galaxies",
    (120, 120): "Héros Intergalactique"
}

# Icônes associées à chaque catégorie d'âge
AGE_CATEGORY_ICONS = {
    "Mini Big Bang": "mdi:star-shooting",
    "Bébé Fusée": "mdi:rocket",
    "Tornade de Gribouilles": "mdi:draw",
    "Pirate des Bacs à Sable": "mdi:shovel",
    "Ninja des Gâteaux": "mdi:cupcake",
    "Roi des Toboggans": "mdi:slide",
    "Artiste des Stickers": "mdi:sticker",
    "Champion des Roulettes": "mdi:bicycle",
    "Maître des Legos": "mdi:toy-brick",
    "Empereur des Cabanes": "mdi:home-roof",
    "As des Cartes Pokémon": "mdi:pokeball",
    "Pré-Ado TikTokeur": "mdi:cellphone-play",
    "Rebelle des Émojis": "mdi:emoticon-cool",
    "Guru des Memes": "mdi:emoticon-lol",
    "Ninja des Selfies": "mdi:camera",
    "Philosophe des Hashtags": "mdi:pound",
    "Roi des Stories Snapchat": "mdi:snapchat",
    "Visionnaire des Reels": "mdi:instagram",
    "Majeur": "mdi:account-check",
    "Sorcier des Festivals": "mdi:music",
    "Ninja des Apéros": "mdi:glass-cocktail",
    "Maître des Soirées Impro": "mdi:party-popper",
    "Jedi des Group Chats": "mdi:chat",
    "Guru des Playlists Spotify": "mdi:music-note",
    "As des Brunchs": "mdi:food",
    "Super-Héros des To-Do Lists": "mdi:check-all",
    "Rockstar des Dimanches Netflix": "mdi:television-play",
    "Sorcier des Excuses Créatives": "mdi:lightbulb-on",
    "Empereur des Karaokés": "mdi:microphone",
    "Maître des Challenges TikTok": "mdi:cellphone-video",
    "Guru des Brunchs": "mdi:food",
    "Ninja des Réunions Zoom": "mdi:video",
    "Jedi des Spreadsheets": "mdi:table",
    "As des Apéros Vins": "mdi:glass-wine",
    "Super-Héros du Multitasking": "mdi:head-sync",
    "Rockstar des Anniversaires": "mdi:cake",
    "Sorcier des BBQ": "mdi:grill",
    "Maître des Blagues Carambar": "mdi:emoticon-happy",
    "Empereur des Soirées Quiz": "mdi:help-circle",
    "Guru des Astuces Cuisine": "mdi:chef-hat",
    "Ninja des Parents Débordés": "mdi:run-fast",
    "Jedi des Vacances Planifiées": "mdi:airplane",
    "As des Jeux de Société": "mdi:chess-king",
    "Super-Héros des Excuses Épiques": "mdi:lightbulb-on",
    "Rockstar des Réunions Parents-Profs": "mdi:school",
    "Sorcier des Budgets Serrés": "mdi:cash",
    "Maître des Anecdotes Drôles": "mdi:comment-quote",
    "Empereur des Barbecues": "mdi:grill",
    "Guru des Soirées Nostalgie": "mdi:vinyl",
    "Ninja des Projets DIY": "mdi:hammer",
    "Rockstar des Blagues de Papa": "mdi:emoticon-happy",
    "Jedi des Siestes Impromptues": "mdi:sleep",
    "As des Histoires de Jeunesse": "mdi:book-open",
    "Super-Héros des Années 80": "mdi:cassette",
    "Sorcier des Recettes de Grand-Mère": "mdi:pot-mix",
    "Maître des Jeux de Cartes": "mdi:cards",
    "Empereur des Randonnées": "mdi:hiking",
    "Guru des Conseils Sages": "mdi:owl",
    "Ninja des Soirées Tricot": "mdi:yarn",
    "Jedi des Documentaires": "mdi:television-classic",
    "Rockstar des Siestes Épiques": "mdi:sleep",
    "As des Mots Fléchés": "mdi:pencil",
    "Super-Héros des Jardins": "mdi:flower",
    "Sorcier des Histoires Épiques": "mdi:book-open",
    "Maître des Soirées Scrabble": "mdi:alphabetical",
    "Empereur des Balades": "mdi:walk",
    "Guru des Souvenirs": "mdi:image-album",
    "Ninja des Petits-Enfants": "mdi:human-child",
    "Jedi des Anecdotes": "mdi:comment-quote",
    "As des Soirées Bingo": "mdi:slot-machine",
    "Rockstar des Récits d’Antan": "mdi:book-open",
    "Super-Héros des Potagers": "mdi:carrot",
    "Sorcier des Contes": "mdi:book-open",
    "Maître des Puzzles": "mdi:puzzle",
    "Empereur des Souvenirs": "mdi:image-album",
    "Guru des Balancelles": "mdi:seat",
    "Ninja des Histoires": "mdi:comment-quote",
    "Jedi des Siestes": "mdi:sleep",
    "As des Récits Légendaires": "mdi:book-open",
    "Rockstar des Souvenirs": "mdi:image-album",
    "Sage des Anecdotes Épiques": "mdi:owl",
    "Super-Héros des Récits": "mdi:book-open",
    "Sorcier des Mémoires": "mdi:book-open",
    "Maître des Histoires": "mdi:comment-quote",
    "Empereur des Légendes": "mdi:medal",
    "Guru des Contes Épiques": "mdi:book-open",
    "Ninja des Souvenirs": "mdi:image-album",
    "Jedi des Récits": "mdi:comment-quote",
    "As des Anecdotes": "mdi:book-open",
    "Rockstar des Mémoires": "mdi:image-album",
    "Sage des Légendes": "mdi:owl",
    "Super-Héros des Contes": "mdi:book-open",
    "Sorcier des Souvenirs": "mdi:image-album",
    "Maître des Récits Épiques": "mdi:comment-quote",
    "Empereur des Mémoires": "mdi:medal",
    "Guru des Histoires": "mdi:book-open",
    "Ninja des Légendes": "mdi:run-fast",
    "Jedi des Anecdotes": "mdi:comment-quote",
    "As des Contes": "mdi:book-open",
    "Rockstar des Souvenirs": "mdi:image-album",
    "Légende Cosmique": "mdi:star-circle",
    "Super-Héros Intergalactique": "mdi:rocket",
    "Sorcier des Étoiles": "mdi:star",
    "Maître des Constellations": "mdi:star-circle",
    "Empereur des Galaxies": "mdi:orbit",
    "Guru des Univers": "mdi:universe",
    "Ninja des Comètes": "mdi:meteor",
    "Jedi des Astres": "mdi:star",
    "As des Nébuleuses": "mdi:cloud-circle",
    "Rockstar des Étoiles": "mdi:star-shooting",
    "Sage des Voies Lactées": "mdi:orbit",
    "Super-Héros des Supernovas": "mdi:star-shooting",
    "Sorcier des Pulsars": "mdi:pulse",
    "Maître des Quasars": "mdi:radiobox-marked",
    "Empereur des Trou Noirs": "mdi:circle-off",
    "Guru des Météores": "mdi:meteor",
    "Ninja des Aurores": "mdi:weather-sunset",
    "Jedi des Éclipses": "mdi:moon-waning-crescent",
    "As des Novas": "mdi:star-circle",
    "Rockstar des Galaxies": "mdi:orbit",
    "Héros Intergalactique": "mdi:medal"
}

# Échelons de la médaille du travail
WORK_MEDAL_LEVELS = {
    20: "Argent",
    30: "Vermeil",
    35: "Or",
    40: "Grand Or"
}

# Échelons réduits pour travaux pénibles
WORK_MEDAL_PENIBLE_LEVELS = {
    18: "Argent",
    25: "Vermeil",
    30: "Or",
    35: "Grand Or"
}

WEDDING_ANNIVERSARIES = {
    1: "Noces de Coton",
    2: "Noces de Cuir",
    3: "Noces de Froment",
    4: "Noces de Cire",
    5: "Noces de Bois",
    6: "Noces de Chypre",
    7: "Noces de Laine",
    8: "Noces de Coquelicot",
    9: "Noces de Faïence",
    10: "Noces d'Étain",
    11: "Noces de Corail",
    12: "Noces de Soie",
    13: "Noces de Muguet",
    14: "Noces de Plomb",
    15: "Noces de Cristal",
    16: "Noces de Saphir",
    17: "Noces de Rose",
    18: "Noces de Turquoise",
    19: "Noces de Cretonne",
    20: "Noces de Porcelaine",
    21: "Noces d'Opale",
    22: "Noces de Bronze",
    23: "Noces de Béryl",
    24: "Noces de Satin",
    25: "Noces d'Argent",
    26: "Noces de Jade",
    27: "Noces d'Acajou",
    28: "Noces de Nickel",
    29: "Noces de Velours",
    30: "Noces de Perle",
    31: "Noces de Basane",
    32: "Noces de Cuivre",
    33: "Noces de Porphyre",
    34: "Noces d'Ambre",
    35: "Noces de Rubis",
    36: "Noces de Mousseline",
    37: "Noces de Papier",
    38: "Noces de Mercure",
    39: "Noces de Crêpe",
    40: "Noces d'Émeraude",
    41: "Noces de Fer",
    42: "Noces de Nacre",
    43: "Noces de Flanelle",
    44: "Noces de Topaze",
    45: "Noces de Vermeil",
    46: "Noces de Lavande",
    47: "Noces de Cachemire",
    48: "Noces d'Améthyste",
    49: "Noces de Cèdre",
    50: "Noces d'Or",
    51: "Noces de Camélia",
    52: "Noces de Tourmaline",
    53: "Noces de Merisier",
    54: "Noces de Zibeline",
    55: "Noces d'Orchidée",
    56: "Noces de Lapis-Lazuli",
    57: "Noces d'Azurite",
    58: "Noces d'Érable",
    59: "Noces de Vison",
    60: "Noces de Diamant"
}
